services:
  - type: web
    name: hosjuba-backend
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://devHosjuba:Hosju*2025@hosjuba.XXXX.mongodb.net/?retryWrites=true&w=majority&appName=Hosjuba
      - key: NODE_ENV
        value: production
    autoDeploy: true
